version: '3'

services:
    redis:
        image: redis:alpine
        command: redis-server
        ports:
            - '6379:6379'
    postgres:
        image: postgres:13
        environment:
            - POSTGRES_USER=trellis-developer
            - POSTGRES_PASSWORD=local
        ports:
            - '5432:5432'
