module.exports = {
    projects: [
        '<rootDir>/apps/api',
        '<rootDir>/packages/nx-realm',
        '<rootDir>/packages/angularfire-ngrx',
        '<rootDir>/packages/make-buildable',
        '<rootDir>/apps/ngrx-data-websocket-demo',
        '<rootDir>/packages/ngrx-data-websocket/client',
        '<rootDir>/packages/ngrx-data-websocket/server',
        '<rootDir>/packages/ngrx-data-websocket/core',
        '<rootDir>/packages/ngrx-universal-rehydrate',
        '<rootDir>/apps/ngrx-universal-rehydrate-demo',
        '<rootDir>/packages/ngrx-universal-rehydrate-server',
        '<rootDir>/apps/ngrx-universal-rehydrate-demo-api',
        '<rootDir>/packages/rx-dynamic-component',
        '<rootDir>/apps/rx-dynamic-component-demo',
        '<rootDir>/packages/nest-spectator',
        '<rootDir>/packages/nxls',
        '<rootDir>/apps/conways-game-of-life',
    ],
};
